{% set name = "pandera" %}
{% set version = "0.20.4" %}

package:
  name: pandera-suite
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ccf6178293ef9d4393dc4776e47477e3d2dd51c800ecdfedec67fff50f4ad3c2

build:
  number: 0

outputs:
  - name: pandera-base
    build:
      script:
        - python -m pip install . --no-deps --no-build-isolation -vv

    test:
      requires:
        - pip
      imports:
        - pandera
      commands:
        - pip check

    requirements:
      host:
        - python
        - pip
      run:
        - python
        - numpy >=1.19.0
        - pandas >=1.0
        - typing_extensions >=3.7.4.3
        - typing_inspect >=0.6.0
        - wrapt
        - packaging >=20.0
        - pydantic
        - hypothesis >=6.92.7
        - scipy
        - pyyaml >=5.1
        - frictionless <=5  # v5.* introduces breaking changes
        - pyarrow
        - multimethod <=1.10.0
        - typeguard

  - name: pandera
    test:
      requires:
        - pip
      imports:
        - pandera
      commands:
        - pip check
    requirements:
      run:
        - {{ pin_subpackage('pandera-base', max_pin="x.x.x") }}

  - name: pandera-strategies
    test:
      requires:
        - pip
      imports:
        - pandera
        - pandera.strategies
      commands:
        - pip check
    requirements:
      run:
        - {{ pin_subpackage('pandera-base', max_pin="x.x.x") }}
        - hypothesis >=6.92.7

  - name: pandera-hypotheses
    test:
      requires:
        - pip
      imports:
        - pandera
        - pandera.api.hypotheses
      commands:
        - pip check
    requirements:
      run:
        - {{ pin_subpackage('pandera-base', max_pin="x.x.x") }}
        - scipy

  - name: pandera-io
    test:
      requires:
        - pip
      imports:
        - pandera
        - pandera.io
      commands:
        - pip check
    requirements:
      run:
        - {{ pin_subpackage('pandera-base', max_pin="x.x.x") }}
        - pyyaml >=5.1
        - black
        - frictionless
        - click <7.2.0  # frictionless dependency, not a pandera dependency

  - name: pandera-pyspark
    test:
      requires:
        - pip
      imports:
        - pandera
        - pandera.accessors.pyspark_accessor
        - pandera.typing.pyspark
      commands:
        - pip check
    requirements:
      run:
        - {{ pin_subpackage('pandera-base', max_pin="x.x.x") }}
        - pyspark >=3.2.0

  - name: pandera-modin
    test:
      requires:
        - pip
      imports:
        - pandera
        - pandera.accessors.modin_accessor
        - pandera.typing.modin
      commands:
        - pip check
    requirements:
      run:
        - {{ pin_subpackage('pandera-base', max_pin="x.x.x") }}
        - modin
        - protobuf

  - name: pandera-modin-ray
    test:
      requires:
        - pip
      imports:
        - pandera
        - pandera.accessors.modin_accessor
        - pandera.typing.modin
      commands:
        - pip check
    requirements:
      run:
        - {{ pin_subpackage('pandera-base', max_pin="x.x.x") }}
        - modin-ray

  - name: pandera-modin-dask
    test:
      requires:
        - pip
      imports:
        - pandera
        - pandera.accessors.modin_accessor
        - pandera.typing.modin
      commands:
        - pip check
    requirements:
      run:
        - {{ pin_subpackage('pandera-base', max_pin="x.x.x") }}
        - modin-dask

  - name: pandera-dask
    test:
      requires:
        - pip
      imports:
        - pandera
        - pandera.accessors.dask_accessor
        - pandera.typing.dask
      commands:
        - pip check
    requirements:
      run:
        - {{ pin_subpackage('pandera-base', max_pin="x.x.x") }}
        - dask
        - distributed

  - name: pandera-mypy
    test:
      requires:
        - pip
      imports:
        - pandera
        - pandera.mypy
      commands:
        - pip check
    requirements:
      run:
        - {{ pin_subpackage('pandera-base', max_pin="x.x.x") }}
        - mypy
        - pandas-stubs

  - name: pandera-fastapi
    test:
      requires:
        - pip
      imports:
        - pandera
        - pandera.typing.fastapi
      commands:
        - pip check
    requirements:
      run:
        - {{ pin_subpackage('pandera-base', max_pin="x.x.x") }}
        - fastapi

  - name: pandera-geopandas
    test:
      requires:
        - pip
      imports:
        - pandera
        - pandera.typing.geopandas
      commands:
        - pip check
    requirements:
      run:
        - {{ pin_subpackage('pandera-base', max_pin="x.x.x") }}
        - geopandas
        - shapely

about:
  home: https://github.com/pandera-dev/pandera
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: The open source framework for precision data testing
  description: |
    A simple, zero-configuration Python library to help you build
    confidence in the quality of your dataframe-like containers through
    data validation and property-based testing.
  doc_url: https://pandera.readthedocs.io/en/latest/
  dev_url: https://github.com/unionai-oss/pandera

extra:
  feedstock-name: pandera
  recipe-maintainers:
    - cosmicBboy
