{% set name = "pandera" %}
{% set version = "0.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eb0efb6e8d7d1a5edfbf15d8e8c8c0958c27484a98cffcd371ef688707b0b19c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - autopep8
    - black
    - numpy
    - pandas
    - pyyaml
    - scipy
    - wrapt

test:
  imports:
    - pandera

about:
  home: https://github.com/pandera-dev/pandera
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Light-weight and flexible validation for pandas data structures
  description: |
    Pandas data structures hide a lot of information, and explicitly
    validating them in production-critical or reproducible research
    settings is a good idea.
  doc_url: https://pandera.readthedocs.io/en/latest/
  dev_url: https://github.com/pandera-dev/pandera

extra:
  recipe-maintainers:
    - cosmicBboy
