{% set name = "pandera" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6275e85a3102141ad8b0c6559e54416af3991f191f301483900113e67e7a923c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - numpy
    - pandas
    - scipy
    - wrapt

test:
  imports:
    - pandera

about:
  home: https://github.com/pandera-dev/pandera
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Light-weight and flexible validation for pandas data structures
  description: |
    Pandas data structures hide a lot of information, and explicitly
    validating them in production-critical or reproducible research
    settings is a good idea.
  doc_url: https://pandera.readthedocs.io/en/latest/
  dev_url: https://github.com/pandera-dev/pandera

extra:
  recipe-maintainers:
    - cosmicBboy
